myset = set()
myset.add(1)
myset.add(2)
myset.add(3)
myset.add(3)
print(myset)
myset1 = set([1, 2, 3])
myset1.update([4, 5, 6])
print(myset1)
myset1.remove(1)
print(myset1)
myset1.discard(6)
print(myset1)
myset1.clear()
print(myset1)